# Customise this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.61.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :unit_tests do
    gradle(task: "test")
    gradle(task: "connectedAndroidTest")
  end

  desc "Clean"
  lane :clean do
  	gradle(task: "clean")
  end

  desc "Submit a new Alpha DTN Instant Market build to Google Play"
  lane :upload_instant_market_alpha do
    gradle(task: "assembleStockinstantmarketRelease")
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    supply(apk: apk_path, track: 'alpha',skip_upload_images: true,
      skip_upload_screenshots: true)
  end

  desc "Submit a new Alpha FinanceX Build to Google Play"
  lane :upload_financex_alpha do
    gradle(task: "assembleRelease")
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    supply(apk: apk_path, track: 'alpha',skip_upload_images: true,
      skip_upload_screenshots: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
